name: Package Extension

on:
    push:
      tags:
        - 'v*.*.*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependecies
        run: bun install

      - name: Package Extension
        run: bun run package

      - name: Release the pdf
        uses: ncipollo/release-action@v1
        with:
         artifacts: "*.vsix"
         allowUpdates: true